spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

accounts:
  message: "Welcome to SynergyBank Accounts Production API"
  contactDetails:
    name: "Sumit K- Product Owner"
    email: "sumit@test.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1234
