spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

accounts:
  message: "Welcome to SynergyBank Accounts QA API"
  contactDetails:
    name: "Sumit K - QA Lead"
    email: "sumit@test.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1234

