server:
  port: 8090
spring:
  application:
    name: cards
  h2:
    console:
      enabled : true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
config:
  import:
    - "application_qa.yaml"
    - "application_prod.yaml"
  profiles:
    active:
      - "prod"

build:
  version: "3.0"

cards:
  message: "Welcome to SynergyBank Cards Local API"
  contactDetails:
    name: "Sumit K- Developer"
    email: "sumit@test.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1234