spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

accounts:
  message: "Welcome to Employee Prod API"
  contactDetails:
    name: "Silkie Product Owner"
    email: "sk"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1234
