spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

accounts:
  message: "Welcome to payroll Prod API"
  contactDetails:
    name: "Parneet and Mansi Product Owner"
    email: "shaileshgrathod0812@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1234
